# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ClubName.delete_all
ClubName.connection.execute("delete from sqlite_sequence where name='club_names'")
ClubName.create(name: "野球部", sort: 1)
ClubName.create(name: "バレーボール部", sort: 2)
ClubName.create(name: "男子バスケットボール部", sort: 3)
ClubName.create(name: "女子バスケットボール部", sort: 4)
ClubName.create(name: "卓球部", sort: 5)
ClubName.create(name: "女子ソフトテニス部", sort: 6)
ClubName.create(name: "陸上競技部", sort: 7)
ClubName.create(name: "バトミントン部", sort: 8)
ClubName.create(name: "ソフトボール部", sort: 9)
ClubName.create(name: "剣道部", sort: 10)
ClubName.create(name: "弓道部", sort: 11)
ClubName.create(name: "サッカー部", sort: 12)
ClubName.create(name: "文芸部", sort: 13)
ClubName.create(name: "美術部", sort: 14)
ClubName.create(name: "写真部", sort: 15)
ClubName.create(name: "茶道部", sort: 16)
ClubName.create(name: "華道部", sort: 17)
ClubName.create(name: "吹奏楽部", sort: 18)
ClubName.create(name: "経済調査部", sort: 19)
ClubName.create(name: "珠算部", sort: 20)
ClubName.create(name: "ワープロ・コンピューターコンピュータ部", sort: 21)
ClubName.create(name: "放送部", sort: 22)
ClubName.create(name: "簿記部", sort: 23)
ClubName.create(name: "合唱同好会", sort: 24)
ClubName.create(name: "調理同好会", sort: 25)
ClubName.create(name: "ダンス同好会", sort: 26)

Place.delete_all
Place.connection.execute("delete from sqlite_sequence where name='places'")
Place.create(name: "体育館下 入り口前", sort: 0)
Place.create(name: "体育館下 卓球場前北側", sort: 0)
Place.create(name: "体育館下 卓球場前南側", sort: 0)
Place.create(name: "体育館下 剣道場前", sort: 0)
Place.create(name: "体育館 ギャラリー西側	", sort: 0)
Place.create(name: "体育館 ギャラリー東側", sort: 0)
Place.create(name: "部室前 北側	", sort: 0)
Place.create(name: "部室前 南側", sort: 0)
Place.create(name: "グラウンド 野球場", sort: 0)
Place.create(name: "グラウンド 陸上トラック", sort: 0)
Place.create(name: "体育館 北側１", sort: 0)
Place.create(name: "体育館 北側２", sort: 0)
Place.create(name: "体育館 南側", sort: 0)
Place.create(name: "テニスコート", sort: 0)
Place.create(name: "室内練習場", sort: 0)
Place.create(name: "剣道場", sort: 0)
Place.create(name: "卓球場", sort: 0)
Place.create(name: "ウエイトルーム", sort: 0)
Place.create(name: "グラウンド サッカー場", sort: 0)
Place.create(name: "音楽室", sort: 0)
Place.create(name: "第１PC室", sort: 0)
Place.create(name: "第２PC室", sort: 0)
Place.create(name: "第３PC室", sort: 0)
Place.create(name: "デバッグ室", sort: 0)
Place.create(name: "１年教室", sort: 0)
Place.create(name: "２年教室", sort: 0)
Place.create(name: "３年教室", sort: 0)
Place.create(name: "体育館 階段", sort: 0)
Place.create(name: "第１演習室", sort: 0)
Place.create(name: "第２演習室", sort: 0)
Place.create(name: "第３演習室", sort: 0)
Place.create(name: "第４演習室", sort: 0)
Place.create(name: "第５演習室", sort: 0)
Place.create(name: "総合実践室", sort: 0)
Place.create(name: "茶道室", sort: 0)